{% set name = "meta-rdkit-postgresql" %}
{% set version = "2021.03.3" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/motoharu-yano/rdkit.git
    git_tag: Release_2021_03_3_pg_patch
    folder: rdkit_postgresql_src

  - git_url: https://github.com/motoharu-yano/pgsql-gzip.git
    git_tag: master
    folder: pgsql_gzip_postgresql_src

build:
  number: 0

requirements:
  build:
    - python {{ python }}                # [build_platform != target_platform]
    - cross-python_{{ target_platform }} # [build_platform != target_platform]
    - numpy                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - jom   [win]
    - make   [unix]
    - pkg-config   [unix]
  host:
    - python {{ python }}
    - libboost {{ libboost }}
    - boost-cpp
    - eigen
    - freetype
    - tzcode          # [not win]
    - tzdata          # [not win]
    - zlib
    # you need to make sure that conda-forge is added as lower priority channel
    # in this case build will take postgresql from conda-forge because dependent postgresql-plpython is only on conda-forge
    # other packages will be taken from default channels as usual
    # replacing channel with conda build -c conda-forge does not work
    # it forces this channel for all the packages and cartridge fails to pass the tests
    - postgresql {{ postgresql }}
    - postgresql-plpython
    # msys chunk with diffutils is needed for tests
    - msys2-conda-epoch >=20160418 [win]
    - m2-msys2-runtime [win]
    - m2-libiconv [win]
    - m2-libintl [win]
    - m2-diffutils [win]
    - m2-patch [win]
  run:
    # drag python into dependencies - python version is needed for plpython and for rdkit 
    # there are build issues for different combinations of rdkit version + postgresql + python where cartridge may crash on tests
    # postgresql-plpython is also dragged into dependencies - better to install all extensions together with postgresql
    - python {{ python }}
    - libboost {{ libboost }}
    # you need to make sure that conda-forge is added as lower priority channel
    # in this case build will take postgresql from conda-forge because dependent postgresql-plpython is only on conda-forge
    # other packages will be taken from default channels as usual
    # replacing channel with conda build -c conda-forge does not work
    # it forces this channel for all the packages and cartridge fails to pass the tests
    - postgresql {{ postgresql }}
    - postgresql-plpython
    - freetype
    - tzcode          # [not win]
    - tzdata          # [not win]

outputs:
  - name: meta-rdkit-postgresql

about:
  home: https://github.com/motoharu-yano/conda-rdkit
  license: 
  license_file: 
  summary: meta package with conda-forge version of postgresql. contains postgresql-plpython, rdkit-postgresql, pgsql-gzip-postgresql extensions.
  doc_url: https://github.com/motoharu-yano/conda-rdkit/blob/master/README.rst
  dev_url: https://github.com/motoharu-yano/conda-rdkit

extra:
  recipe-maintainers:
    - motoharu-yano
