{% set package_name = "meta-rdkit-postgresql" %}
{% set rdkit_version = "2021.03.3" %}
{% set rdkit_filename = "Release_%s.tar.gz" % rdkit_version.replace(".", "_") %}

package:
  name: {{ package_name|lower }}
  version: {{ rdkit_version }}

source:
  - url: https://github.com/rdkit/rdkit/archive/{{ rdkit_filename }}
    # versions 03.4 and 03.5 do not pass the tests - postgresql crashes
    # 2021.03.1
    #sha256: 9495f797a54ac70b3b6e12776de7d82acd7f7b5d5f0cc1f168c763215545610b
    # 2021.03.2
    #sha256: 9907a745405cc915c65504046e446199f8ad03d870714de57c27d3738f330fe4
    # 2021.03.3
    sha256: e95f07adaee9280df077cb147210ee75e16957d81687ab0836d62ebf1f6f715f
    # 2021.03.4
    #sha256: bed309df7f1e2ea25736a986cf951325681142ee49468b1c62d020a109d2ef52
    # 2021.03.5
    #sha256: ee7ed4189ab03cf805ab9db59121ab3ebcba4c799389d053046d7cab4dd8401e
    folder: rdkit_postgresql_src

  - git_url: https://github.com/motoharu-yano/pgsql-gzip.git
    git_tag: master
    folder: pgsql_gzip_postgresql_src

requirements:
  build:
    - python {{ python }}
  host:
    - python {{ python }}
  run:
    - python {{ python }}
    - rdkit-postgresql
    - pgsql-gzip-postgresql

outputs:
  - name: rdkit-postgresql
    
    build:
      run_exports:
        - {{ pin_subpackage('rdkit-postgresql') }}
    requirements:
      build:
        - python {{ python }}                # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - numpy                              # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - jom   [win]
        - make   [unix]
        - pkg-config   [unix]
      host:
        - python {{ python }}
        - libboost {{ libboost }}
        - boost-cpp
        - eigen
        - freetype
        - tzcode          # [not win]
        - tzdata          # [not win]
        - zlib
        - postgresql {{ postgresql }}
        - postgresql-plpython
        - msys2-conda-epoch >=20160418 [win]
        - m2-msys2-runtime [win]
        - m2-libiconv [win]
        - m2-libintl [win]
        - m2-diffutils [win]
        - m2-patch [win]
      run:
        - python {{ python }}
        - libboost {{ libboost }}
        - postgresql {{ postgresql }}
        - postgresql-plpython
        - freetype
        - tzcode          # [not win]
        - tzdata          # [not win]
    script: install_rdkit_postgresql.sh  # [unix]
    script: install_rdkit_postgresql.sh  # [win]
    test:
      commands:
    about:
      home: http://rdkit.org
      license: BSD-3-Clause
      license_file: rdkit_postgresql_src/license.txt
      summary: rdkit cartridge for postgresql. includes conda-forge version of postgresql and postgresql-plpython extension.
      doc_url: http://www.rdkit.org/docs/index.html
      dev_url: https://github.com/rdkit/rdkit

  - name: pgsql-gzip-postgresql
    build:
      run_exports:
        - {{ pin_subpackage('pgsql-gzip-postgresql') }}
    requirements:
      build:
        - python {{ python }}                # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - numpy                              # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - jom   [win]
        - make   [unix]
        - pkg-config   [unix]
      host:
        - python {{ python }}
        - freetype
        - tzcode          # [not win]
        - tzdata          # [not win]
        - zlib
        - postgresql {{ postgresql }}
        - postgresql-plpython
        - msys2-conda-epoch >=20160418 [win]
        - m2-msys2-runtime [win]
        - m2-libiconv [win]
        - m2-libintl [win]
        - m2-diffutils [win]
        - m2-patch [win]
      run:
        - python {{ python }}
        - postgresql {{ postgresql }}
        - postgresql-plpython
        - freetype
        - tzcode          # [not win]
        - tzdata          # [not win]
    script: install_pgsql_gzip_postgresql.sh  # [unix]
    script: install_pgsql_gzip_postgresql.bat  # [win]
    test:
      commands:
    about:
      home: https://github.com/pramsey/pgsql-gzip
      license: MIT License
      license_file: pgsql_gzip_postgresql_src/LICENSE.md
      summary: gzip extension for postgresql. includes conda-forge version of postgresql and postgresql-plpython extension.
      doc_url: https://github.com/motoharu-yano/pgsql-gzip/blob/master/README.md
      dev_url: https://github.com/motoharu-yano/pgsql-gzip

about:
  home: https://github.com/motoharu-yano/conda-rdkit
  license: 
  license_file: 
  summary: meta package with conda-forge version of postgresql. contains postgresql-plpython, rdkit-postgresql, pgsql-gzip-postgresql extensions.
  doc_url: https://github.com/motoharu-yano/conda-rdkit/blob/master/README.rst
  dev_url: https://github.com/motoharu-yano/conda-rdkit

extra:
  recipe-maintainers:
    - motoharu-yano
