package:
  name: rdkit
  # This is the real version, used in releases:
  # version is the last TAG + the number of commits since
  # version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL').replace("_", ".").replace("Release.","") }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # This is the version used for the nightlies:
  version: 2021.09.1b.{{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  # version: 2021.03.1.{{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}


source:
  git_url: https://github.com/rdkit/rdkit.git
  #git_rev: Release_2021_03
  git_rev: master
  patches:
    - rdpaths.patch

build:
  number: 1

requirements:
  build:
    - requests
    - {{ compiler('cxx') }}
    - python
    - m2-patch [win]
    - cmake
  host:
    - libboost {{ libboost }}
    - boost-cpp
    - py-boost {{ libboost }}
    - python
    - numpy
    - pillow
    - freetype
    - nox [linux]
    - cairo
    - pkg-config [unix]
    - eigen
    - pandas
  run:
    - libboost
    - py-boost
    - cairo
    - python
    - pillow
    - pandas
    - numpy >=1.12
test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
